server:
  port: 9100

spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true
    user:
      name: root
      password: root

eureka:
  instance:
    hostname: 127.0.0.1

  client:
    #客户端调用地址
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: true
    fetch-registry: true

  server:
    #禁用自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000