server:
  port: 8082

item:
  #url: http://127.0.0.1:8081/item/
  url: http://app-item/item/

#服务名称
spring:
  application:
    name: app-order
#注册地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@127.0.0.1:8100/eureka,http://root:root@127.0.0.1:9100/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: 订单服务[order-demo]:${server.port}