server:
  port: 8081

#MySQL8.0+
#spring:datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=root
## Hikari 数据源专用配置
##spring.datasource.hikari.maximum-pool-size=20
##spring.datasource.hikari.minimum-idle=5
## JPA 相关配置
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


spring:
  # mySQL5.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  # MongoDB
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: demo
#      username: root
#      password: root

mybatis:
  # 指定POJO扫描包
  type-aliases-package: com.oyf.mysql_aes.entity
  # 指定mapper.xml扫描路径
  mapper-locations: mapper/**.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true




