server:
  port: 8081
#服务名称(该服务注册到eureka注册中心的名称)
spring:
  application:
    name: app-item
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      #http://username:passport@ip:port/
      defaultZone: http://root:root@127.0.0.1:8100/eureka,http://root:root@127.0.0.1:9100/eureka
    #因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    #是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: 商品服务[item-demo]:${server.port}