server:
  port: 8021
spring:
  application:
    name: rabbitmq-provider
  #配置rabbitMq服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    template:
      mandatory: true